// Shortcuts data extracted from server/storage.ts
export const shortcutsData = [
  // Windows OS
  {
    tool: "Windows",
    category: "os",
    title: "복사",
    description: "선택한 항목을 클립보드에 복사",
    windowsShortcut: "Ctrl+C",
    macosShortcut: "Cmd+C",
    linuxShortcut: "Ctrl+C",
    popularity: 100,
    verified: true,
    aliases: ["copy", "복사하기"],
    tags: ["clipboard", "basic"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "붙여넣기",
    description: "클립보드의 내용을 붙여넣기",
    windowsShortcut: "Ctrl+V",
    macosShortcut: "Cmd+V",
    linuxShortcut: "Ctrl+V",
    popularity: 95,
    verified: true,
    aliases: ["paste", "붙여넣기"],
    tags: ["clipboard", "basic"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "작업 관리자",
    description: "작업 관리자 열기",
    windowsShortcut: "Ctrl+Shift+Esc",
    macosShortcut: "Cmd+Option+Esc",
    linuxShortcut: "Ctrl+Alt+Del",
    popularity: 85,
    verified: true,
    aliases: ["task manager", "작업관리자"],
    tags: ["system", "management"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "스크린샷",
    description: "부분 스크린샷 캡처",
    windowsShortcut: "Win+Shift+S",
    macosShortcut: "Cmd+Shift+4",
    linuxShortcut: "Shift+PrtSc",
    popularity: 80,
    verified: true,
    aliases: ["screenshot", "캡처"],
    tags: ["capture", "screen"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "잠금 화면",
    description: "컴퓨터 잠금",
    windowsShortcut: "Win+L",
    macosShortcut: "Cmd+Ctrl+Q",
    linuxShortcut: "Ctrl+Alt+L",
    popularity: 75,
    verified: true,
    aliases: ["lock", "잠금"],
    tags: ["security", "lock"]
  },
  
  // VSCode
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "명령 팔레트",
    description: "모든 명령에 빠르게 액세스",
    windowsShortcut: "Ctrl+Shift+P",
    macosShortcut: "Cmd+Shift+P",
    linuxShortcut: "Ctrl+Shift+P",
    popularity: 90,
    verified: true,
    aliases: ["command palette", "명령어"],
    tags: ["navigation", "command"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "빠른 열기",
    description: "파일 또는 기호로 이동",
    windowsShortcut: "Ctrl+P",
    macosShortcut: "Cmd+P",
    linuxShortcut: "Ctrl+P",
    popularity: 85,
    verified: true,
    aliases: ["quick open", "파일열기"],
    tags: ["navigation", "file"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "다중 커서",
    description: "다음 일치 항목 선택",
    windowsShortcut: "Ctrl+D",
    macosShortcut: "Cmd+D",
    linuxShortcut: "Ctrl+D",
    popularity: 80,
    verified: true,
    aliases: ["multi cursor", "다중선택"],
    tags: ["editing", "selection"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "터미널 토글",
    description: "통합 터미널 보기/숨기기",
    windowsShortcut: "Ctrl+`",
    macosShortcut: "Cmd+`",
    linuxShortcut: "Ctrl+`",
    popularity: 75,
    verified: true,
    aliases: ["terminal", "터미널"],
    tags: ["terminal", "toggle"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "사이드바 토글",
    description: "사이드바 보기/숨기기",
    windowsShortcut: "Ctrl+B",
    macosShortcut: "Cmd+B",
    linuxShortcut: "Ctrl+B",
    popularity: 70,
    verified: true,
    aliases: ["sidebar", "사이드바"],
    tags: ["view", "sidebar"]
  },
  
  // Excel
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "자동 합계",
    description: "선택한 셀의 합계 자동 계산",
    windowsShortcut: "Alt+=",
    macosShortcut: "Cmd+=",
    linuxShortcut: "Alt+=",
    popularity: 90,
    verified: true,
    aliases: ["autosum", "합계"],
    tags: ["formula", "calculation"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "셀 서식",
    description: "셀 서식 대화상자 열기",
    windowsShortcut: "Ctrl+1",
    macosShortcut: "Cmd+1",
    linuxShortcut: "Ctrl+1",
    popularity: 85,
    verified: true,
    aliases: ["format cells", "서식"],
    tags: ["formatting", "cells"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "필터",
    description: "자동 필터 토글",
    windowsShortcut: "Ctrl+Shift+L",
    macosShortcut: "Cmd+Shift+L",
    linuxShortcut: "Ctrl+Shift+L",
    popularity: 80,
    verified: true,
    aliases: ["filter", "필터링"],
    tags: ["data", "filter"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "행 삽입",
    description: "새 행 삽입",
    windowsShortcut: "Ctrl+Shift++",
    macosShortcut: "Cmd+Shift++",
    linuxShortcut: "Ctrl+Shift++",
    popularity: 75,
    verified: true,
    aliases: ["insert row", "행추가"],
    tags: ["editing", "row"]
  },
  
  // Photoshop
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "브러시 도구",
    description: "브러시 도구 선택",
    windowsShortcut: "B",
    macosShortcut: "B",
    linuxShortcut: "B",
    popularity: 85,
    verified: true,
    aliases: ["brush tool", "브러시"],
    tags: ["tool", "brush"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "변형",
    description: "자유 변형 모드",
    windowsShortcut: "Ctrl+T",
    macosShortcut: "Cmd+T",
    linuxShortcut: "Ctrl+T",
    popularity: 80,
    verified: true,
    aliases: ["transform", "변형"],
    tags: ["transform", "editing"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "새 레이어",
    description: "새 레이어 만들기",
    windowsShortcut: "Ctrl+Shift+N",
    macosShortcut: "Cmd+Shift+N",
    linuxShortcut: "Ctrl+Shift+N",
    popularity: 75,
    verified: true,
    aliases: ["new layer", "레이어"],
    tags: ["layer", "new"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "레이어 복제",
    description: "현재 레이어 복제",
    windowsShortcut: "Ctrl+J",
    macosShortcut: "Cmd+J",
    linuxShortcut: "Ctrl+J",
    popularity: 70,
    verified: true,
    aliases: ["duplicate layer", "복제"],
    tags: ["layer", "duplicate"]
  },
  
  // Chrome
  {
    tool: "Google Chrome",
    category: "browser",
    title: "새 탭",
    description: "새 탭 열기",
    windowsShortcut: "Ctrl+T",
    macosShortcut: "Cmd+T",
    linuxShortcut: "Ctrl+T",
    popularity: 95,
    verified: true,
    aliases: ["new tab", "새탭"],
    tags: ["navigation", "tab"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "탭 닫기",
    description: "현재 탭 닫기",
    windowsShortcut: "Ctrl+W",
    macosShortcut: "Cmd+W",
    linuxShortcut: "Ctrl+W",
    popularity: 90,
    verified: true,
    aliases: ["close tab", "탭닫기"],
    tags: ["navigation", "tab"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "새로고침",
    description: "페이지 새로고침",
    windowsShortcut: "Ctrl+R",
    macosShortcut: "Cmd+R",
    linuxShortcut: "Ctrl+R",
    popularity: 85,
    verified: true,
    aliases: ["refresh", "새로고침"],
    tags: ["navigation", "refresh"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "개발자 도구",
    description: "개발자 도구 열기",
    windowsShortcut: "F12",
    macosShortcut: "Cmd+Option+I",
    linuxShortcut: "F12",
    popularity: 80,
    verified: true,
    aliases: ["developer tools", "개발자도구"],
    tags: ["development", "tools"]
  },
  
  // PyCharm
  {
    tool: "PyCharm",
    category: "ide",
    title: "코드 실행",
    description: "현재 파일 실행",
    windowsShortcut: "Shift+F10",
    macosShortcut: "Ctrl+R",
    linuxShortcut: "Shift+F10",
    popularity: 90,
    verified: true,
    aliases: ["run code", "실행"],
    tags: ["execution", "run"]
  },
  {
    tool: "PyCharm",
    category: "ide",
    title: "디버그",
    description: "디버그 모드로 실행",
    windowsShortcut: "Shift+F9",
    macosShortcut: "Ctrl+D",
    linuxShortcut: "Shift+F9",
    popularity: 85,
    verified: true,
    aliases: ["debug", "디버깅"],
    tags: ["debugging", "debug"]
  },
  {
    tool: "PyCharm",
    category: "ide",
    title: "리팩토링",
    description: "리팩토링 메뉴 열기",
    windowsShortcut: "Ctrl+Alt+Shift+T",
    macosShortcut: "Ctrl+T",
    linuxShortcut: "Ctrl+Alt+Shift+T",
    popularity: 75,
    verified: true,
    aliases: ["refactor", "리팩토링"],
    tags: ["refactoring", "code"]
  },
  
  // Jupyter
  {
    tool: "Jupyter Notebook",
    category: "ide",
    title: "셀 실행",
    description: "셀 실행 후 다음 셀로 이동",
    windowsShortcut: "Shift+Enter",
    macosShortcut: "Shift+Enter",
    linuxShortcut: "Shift+Enter",
    popularity: 95,
    verified: true,
    aliases: ["run cell", "셀실행"],
    tags: ["execution", "cell"]
  },
  {
    tool: "Jupyter Notebook",
    category: "ide",
    title: "새 셀 삽입",
    description: "아래에 새 셀 삽입",
    windowsShortcut: "B",
    macosShortcut: "B",
    linuxShortcut: "B",
    popularity: 80,
    verified: true,
    aliases: ["insert cell", "셀삽입"],
    tags: ["cell", "insert"]
  },
  {
    tool: "Jupyter Notebook",
    category: "ide",
    title: "셀 삭제",
    description: "현재 셀 삭제",
    windowsShortcut: "DD",
    macosShortcut: "DD",
    linuxShortcut: "DD",
    popularity: 70,
    verified: true,
    aliases: ["delete cell", "셀삭제"],
    tags: ["cell", "delete"]
  },
  
  // Slack
  {
    tool: "Slack",
    category: "communication",
    title: "빠른 스위처",
    description: "채널/DM 빠른 검색",
    windowsShortcut: "Ctrl+K",
    macosShortcut: "Cmd+K",
    linuxShortcut: "Ctrl+K",
    popularity: 85,
    verified: true,
    aliases: ["quick switcher", "빠른검색"],
    tags: ["navigation", "search"]
  },
  {
    tool: "Slack",
    category: "communication",
    title: "모든 읽지 않은 메시지",
    description: "읽지 않은 메시지 표시",
    windowsShortcut: "Ctrl+Shift+A",
    macosShortcut: "Cmd+Shift+A",
    linuxShortcut: "Ctrl+Shift+A",
    popularity: 75,
    verified: true,
    aliases: ["unread messages", "읽지않은메시지"],
    tags: ["messages", "unread"]
  },
  
  // Discord
  {
    tool: "Discord",
    category: "communication",
    title: "서버 검색",
    description: "서버 및 채널 검색",
    windowsShortcut: "Ctrl+K",
    macosShortcut: "Cmd+K",
    linuxShortcut: "Ctrl+K",
    popularity: 80,
    verified: true,
    aliases: ["search", "서버검색"],
    tags: ["navigation", "search"]
  },
  {
    tool: "Discord",
    category: "communication",
    title: "음소거 토글",
    description: "마이크 음소거 토글",
    windowsShortcut: "Ctrl+Shift+M",
    macosShortcut: "Cmd+Shift+M",
    linuxShortcut: "Ctrl+Shift+M",
    popularity: 75,
    verified: true,
    aliases: ["mute", "음소거"],
    tags: ["audio", "mute"]
  },
  
  // Figma
  {
    tool: "Figma",
    category: "design",
    title: "선택 도구",
    description: "선택 도구로 변경",
    windowsShortcut: "V",
    macosShortcut: "V",
    linuxShortcut: "V",
    popularity: 90,
    verified: true,
    aliases: ["select tool", "선택도구"],
    tags: ["tool", "select"]
  },
  {
    tool: "Figma",
    category: "design",
    title: "프레임 도구",
    description: "프레임 도구로 변경",
    windowsShortcut: "F",
    macosShortcut: "F",
    linuxShortcut: "F",
    popularity: 85,
    verified: true,
    aliases: ["frame tool", "프레임도구"],
    tags: ["tool", "frame"]
  },
  
  // Notion
  {
    tool: "Notion",
    category: "productivity",
    title: "빠른 찾기",
    description: "페이지 빠른 검색",
    windowsShortcut: "Ctrl+P",
    macosShortcut: "Cmd+P",
    linuxShortcut: "Ctrl+P",
    popularity: 85,
    verified: true,
    aliases: ["quick find", "빠른찾기"],
    tags: ["navigation", "search"]
  },
  {
    tool: "Notion",
    category: "productivity",
    title: "새 페이지",
    description: "새 페이지 만들기",
    windowsShortcut: "Ctrl+N",
    macosShortcut: "Cmd+N",
    linuxShortcut: "Ctrl+N",
    popularity: 80,
    verified: true,
    aliases: ["new page", "새페이지"],
    tags: ["page", "new"]
  },
  
  // Terminal
  {
    tool: "Terminal",
    category: "os",
    title: "화면 지우기",
    description: "터미널 화면 지우기",
    windowsShortcut: "Ctrl+L",
    macosShortcut: "Cmd+K",
    linuxShortcut: "Ctrl+L",
    popularity: 85,
    verified: true,
    aliases: ["clear screen", "화면지우기"],
    tags: ["terminal", "clear"]
  },
  {
    tool: "Terminal",
    category: "os",
    title: "프로세스 중단",
    description: "실행 중인 프로세스 중단",
    windowsShortcut: "Ctrl+C",
    macosShortcut: "Cmd+C",
    linuxShortcut: "Ctrl+C",
    popularity: 80,
    verified: true,
    aliases: ["interrupt", "중단"],
    tags: ["terminal", "interrupt"]
  },
  
  // More Windows shortcuts
  {
    tool: "Windows",
    category: "os",
    title: "실행 대화상자",
    description: "실행 대화상자 열기",
    windowsShortcut: "Win+R",
    macosShortcut: null,
    linuxShortcut: null,
    popularity: 90,
    verified: true,
    aliases: ["run dialog", "실행"],
    tags: ["system", "run"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "파일 탐색기",
    description: "파일 탐색기 열기",
    windowsShortcut: "Win+E",
    macosShortcut: "Cmd+Space",
    linuxShortcut: "Ctrl+Alt+F",
    popularity: 85,
    verified: true,
    aliases: ["file explorer", "탐색기"],
    tags: ["file", "explorer"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "설정",
    description: "Windows 설정 열기",
    windowsShortcut: "Win+I",
    macosShortcut: "Cmd+,",
    linuxShortcut: null,
    popularity: 80,
    verified: true,
    aliases: ["settings", "설정"],
    tags: ["system", "settings"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "데스크톱 보기",
    description: "모든 창 최소화하여 데스크톱 보기",
    windowsShortcut: "Win+D",
    macosShortcut: "F11",
    linuxShortcut: "Ctrl+Alt+D",
    popularity: 75,
    verified: true,
    aliases: ["show desktop", "데스크톱"],
    tags: ["desktop", "minimize"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "창 전환",
    description: "열린 창 사이 전환",
    windowsShortcut: "Alt+Tab",
    macosShortcut: "Cmd+Tab",
    linuxShortcut: "Alt+Tab",
    popularity: 95,
    verified: true,
    aliases: ["switch window", "창전환"],
    tags: ["window", "switch"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "전체 화면 스크린샷",
    description: "전체 화면 스크린샷 찍기",
    windowsShortcut: "PrtSc",
    macosShortcut: "Cmd+Shift+3",
    linuxShortcut: "PrtSc",
    popularity: 85,
    verified: true,
    aliases: ["screenshot", "화면캡처"],
    tags: ["capture", "screen"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "창 닫기",
    description: "현재 창 닫기",
    windowsShortcut: "Alt+F4",
    macosShortcut: "Cmd+W",
    linuxShortcut: "Alt+F4",
    popularity: 90,
    verified: true,
    aliases: ["close window", "창닫기"],
    tags: ["window", "close"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "검색",
    description: "Windows 검색 열기",
    windowsShortcut: "Win+S",
    macosShortcut: "Cmd+Space",
    linuxShortcut: "Alt+F1",
    popularity: 80,
    verified: true,
    aliases: ["search", "검색"],
    tags: ["search", "find"]
  },
  {
    tool: "Windows",
    category: "os",
    title: "가상 데스크톱",
    description: "새 가상 데스크톱 만들기",
    windowsShortcut: "Win+Ctrl+D",
    macosShortcut: "Ctrl+Up",
    linuxShortcut: "Ctrl+Alt+T",
    popularity: 65,
    verified: true,
    aliases: ["virtual desktop", "가상데스크톱"],
    tags: ["desktop", "virtual"]
  },

  // More VSCode shortcuts
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "전체 줄 선택",
    description: "현재 줄 전체 선택",
    windowsShortcut: "Ctrl+L",
    macosShortcut: "Cmd+L",
    linuxShortcut: "Ctrl+L",
    popularity: 85,
    verified: true,
    aliases: ["select line", "줄선택"],
    tags: ["selection", "line"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "줄 복사",
    description: "현재 줄 복사",
    windowsShortcut: "Shift+Alt+Down",
    macosShortcut: "Shift+Option+Down",
    linuxShortcut: "Shift+Alt+Down",
    popularity: 80,
    verified: true,
    aliases: ["copy line", "줄복사"],
    tags: ["copy", "line"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "줄 이동",
    description: "현재 줄을 위/아래로 이동",
    windowsShortcut: "Alt+Up/Down",
    macosShortcut: "Option+Up/Down",
    linuxShortcut: "Alt+Up/Down",
    popularity: 75,
    verified: true,
    aliases: ["move line", "줄이동"],
    tags: ["move", "line"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "줄 삭제",
    description: "현재 줄 삭제",
    windowsShortcut: "Ctrl+Shift+K",
    macosShortcut: "Cmd+Shift+K",
    linuxShortcut: "Ctrl+Shift+K",
    popularity: 70,
    verified: true,
    aliases: ["delete line", "줄삭제"],
    tags: ["delete", "line"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "주석 토글",
    description: "선택한 줄 주석 토글",
    windowsShortcut: "Ctrl+/",
    macosShortcut: "Cmd+/",
    linuxShortcut: "Ctrl+/",
    popularity: 90,
    verified: true,
    aliases: ["toggle comment", "주석"],
    tags: ["comment", "toggle"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "블록 주석",
    description: "블록 주석 토글",
    windowsShortcut: "Shift+Alt+A",
    macosShortcut: "Shift+Option+A",
    linuxShortcut: "Shift+Alt+A",
    popularity: 75,
    verified: true,
    aliases: ["block comment", "블록주석"],
    tags: ["comment", "block"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "포맷팅",
    description: "문서 포맷팅",
    windowsShortcut: "Shift+Alt+F",
    macosShortcut: "Shift+Option+F",
    linuxShortcut: "Shift+Alt+F",
    popularity: 85,
    verified: true,
    aliases: ["format document", "포맷팅"],
    tags: ["format", "document"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "정의로 이동",
    description: "선택한 심볼의 정의로 이동",
    windowsShortcut: "F12",
    macosShortcut: "F12",
    linuxShortcut: "F12",
    popularity: 80,
    verified: true,
    aliases: ["go to definition", "정의이동"],
    tags: ["navigation", "definition"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "문제 패널",
    description: "문제 패널 열기",
    windowsShortcut: "Ctrl+Shift+M",
    macosShortcut: "Cmd+Shift+M",
    linuxShortcut: "Ctrl+Shift+M",
    popularity: 70,
    verified: true,
    aliases: ["problems panel", "문제패널"],
    tags: ["panel", "problems"]
  },
  {
    tool: "Visual Studio Code",
    category: "ide",
    title: "확장 프로그램",
    description: "확장 프로그램 패널 열기",
    windowsShortcut: "Ctrl+Shift+X",
    macosShortcut: "Cmd+Shift+X",
    linuxShortcut: "Ctrl+Shift+X",
    popularity: 65,
    verified: true,
    aliases: ["extensions", "확장프로그램"],
    tags: ["extensions", "panel"]
  },

  // More Excel shortcuts
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "새 워크시트",
    description: "새 워크시트 추가",
    windowsShortcut: "Shift+F11",
    macosShortcut: "Shift+F11",
    linuxShortcut: "Shift+F11",
    popularity: 70,
    verified: true,
    aliases: ["new worksheet", "새워크시트"],
    tags: ["worksheet", "new"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "셀 편집",
    description: "선택한 셀 편집 모드",
    windowsShortcut: "F2",
    macosShortcut: "F2",
    linuxShortcut: "F2",
    popularity: 85,
    verified: true,
    aliases: ["edit cell", "셀편집"],
    tags: ["cell", "edit"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "현재 날짜",
    description: "현재 날짜 입력",
    windowsShortcut: "Ctrl+;",
    macosShortcut: "Cmd+;",
    linuxShortcut: "Ctrl+;",
    popularity: 75,
    verified: true,
    aliases: ["current date", "날짜입력"],
    tags: ["date", "current"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "현재 시간",
    description: "현재 시간 입력",
    windowsShortcut: "Ctrl+Shift+;",
    macosShortcut: "Cmd+Shift+;",
    linuxShortcut: "Ctrl+Shift+;",
    popularity: 70,
    verified: true,
    aliases: ["current time", "시간입력"],
    tags: ["time", "current"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "아래로 채우기",
    description: "선택한 셀을 아래로 채우기",
    windowsShortcut: "Ctrl+D",
    macosShortcut: "Cmd+D",
    linuxShortcut: "Ctrl+D",
    popularity: 80,
    verified: true,
    aliases: ["fill down", "아래채우기"],
    tags: ["fill", "down"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "오른쪽으로 채우기",
    description: "선택한 셀을 오른쪽으로 채우기",
    windowsShortcut: "Ctrl+R",
    macosShortcut: "Cmd+R",
    linuxShortcut: "Ctrl+R",
    popularity: 75,
    verified: true,
    aliases: ["fill right", "오른쪽채우기"],
    tags: ["fill", "right"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "전체 열 선택",
    description: "전체 열 선택",
    windowsShortcut: "Ctrl+Space",
    macosShortcut: "Cmd+Space",
    linuxShortcut: "Ctrl+Space",
    popularity: 70,
    verified: true,
    aliases: ["select column", "열선택"],
    tags: ["selection", "column"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "전체 행 선택",
    description: "전체 행 선택",
    windowsShortcut: "Shift+Space",
    macosShortcut: "Shift+Space",
    linuxShortcut: "Shift+Space",
    popularity: 70,
    verified: true,
    aliases: ["select row", "행선택"],
    tags: ["selection", "row"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "데이터 끝으로",
    description: "데이터 영역의 끝으로 이동",
    windowsShortcut: "Ctrl+End",
    macosShortcut: "Cmd+End",
    linuxShortcut: "Ctrl+End",
    popularity: 75,
    verified: true,
    aliases: ["go to end", "끝으로이동"],
    tags: ["navigation", "end"]
  },
  {
    tool: "Microsoft Excel",
    category: "office",
    title: "데이터 시작으로",
    description: "데이터 영역의 시작으로 이동",
    windowsShortcut: "Ctrl+Home",
    macosShortcut: "Cmd+Home",
    linuxShortcut: "Ctrl+Home",
    popularity: 70,
    verified: true,
    aliases: ["go to start", "시작으로이동"],
    tags: ["navigation", "start"]
  },

  // More Photoshop shortcuts
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "선택 도구",
    description: "선택 도구 (마키 도구)",
    windowsShortcut: "M",
    macosShortcut: "M",
    linuxShortcut: "M",
    popularity: 90,
    verified: true,
    aliases: ["marquee tool", "선택도구"],
    tags: ["tool", "selection"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "올가미 도구",
    description: "올가미 도구 선택",
    windowsShortcut: "L",
    macosShortcut: "L",
    linuxShortcut: "L",
    popularity: 80,
    verified: true,
    aliases: ["lasso tool", "올가미도구"],
    tags: ["tool", "lasso"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "마법봉 도구",
    description: "마법봉 도구 선택",
    windowsShortcut: "W",
    macosShortcut: "W",
    linuxShortcut: "W",
    popularity: 85,
    verified: true,
    aliases: ["magic wand", "마법봉"],
    tags: ["tool", "magic wand"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "자르기 도구",
    description: "자르기 도구 선택",
    windowsShortcut: "C",
    macosShortcut: "C",
    linuxShortcut: "C",
    popularity: 85,
    verified: true,
    aliases: ["crop tool", "자르기도구"],
    tags: ["tool", "crop"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "스포이드 도구",
    description: "스포이드 도구 선택",
    windowsShortcut: "I",
    macosShortcut: "I",
    linuxShortcut: "I",
    popularity: 80,
    verified: true,
    aliases: ["eyedropper", "스포이드"],
    tags: ["tool", "eyedropper"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "복원 브러시",
    description: "복원 브러시 도구 선택",
    windowsShortcut: "J",
    macosShortcut: "J",
    linuxShortcut: "J",
    popularity: 75,
    verified: true,
    aliases: ["healing brush", "복원브러시"],
    tags: ["tool", "healing"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "확대/축소 도구",
    description: "확대/축소 도구 선택",
    windowsShortcut: "Z",
    macosShortcut: "Z",
    linuxShortcut: "Z",
    popularity: 85,
    verified: true,
    aliases: ["zoom tool", "확대도구"],
    tags: ["tool", "zoom"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "레이어 병합",
    description: "보이는 레이어 병합",
    windowsShortcut: "Ctrl+Shift+E",
    macosShortcut: "Cmd+Shift+E",
    linuxShortcut: "Ctrl+Shift+E",
    popularity: 70,
    verified: true,
    aliases: ["merge layers", "레이어병합"],
    tags: ["layer", "merge"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "레이어 아래로 병합",
    description: "현재 레이어를 아래 레이어와 병합",
    windowsShortcut: "Ctrl+E",
    macosShortcut: "Cmd+E",
    linuxShortcut: "Ctrl+E",
    popularity: 75,
    verified: true,
    aliases: ["merge down", "아래로병합"],
    tags: ["layer", "merge down"]
  },
  {
    tool: "Adobe Photoshop",
    category: "design",
    title: "색상 조정",
    description: "색상/채도 조정",
    windowsShortcut: "Ctrl+U",
    macosShortcut: "Cmd+U",
    linuxShortcut: "Ctrl+U",
    popularity: 80,
    verified: true,
    aliases: ["hue saturation", "색상조정"],
    tags: ["adjustment", "color"]
  },

  // More Chrome shortcuts
  {
    tool: "Google Chrome",
    category: "browser",
    title: "시크릿 모드",
    description: "시크릿 창 열기",
    windowsShortcut: "Ctrl+Shift+N",
    macosShortcut: "Cmd+Shift+N",
    linuxShortcut: "Ctrl+Shift+N",
    popularity: 85,
    verified: true,
    aliases: ["incognito mode", "시크릿모드"],
    tags: ["incognito", "private"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "최근 닫은 탭",
    description: "최근 닫은 탭 다시 열기",
    windowsShortcut: "Ctrl+Shift+T",
    macosShortcut: "Cmd+Shift+T",
    linuxShortcut: "Ctrl+Shift+T",
    popularity: 90,
    verified: true,
    aliases: ["reopen tab", "탭복원"],
    tags: ["tab", "reopen"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "북마크 바",
    description: "북마크 바 토글",
    windowsShortcut: "Ctrl+Shift+B",
    macosShortcut: "Cmd+Shift+B",
    linuxShortcut: "Ctrl+Shift+B",
    popularity: 70,
    verified: true,
    aliases: ["bookmark bar", "북마크바"],
    tags: ["bookmark", "bar"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "주소창 검색",
    description: "주소창에 포커스",
    windowsShortcut: "Ctrl+L",
    macosShortcut: "Cmd+L",
    linuxShortcut: "Ctrl+L",
    popularity: 85,
    verified: true,
    aliases: ["address bar", "주소창"],
    tags: ["address", "focus"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "다음 탭",
    description: "다음 탭으로 이동",
    windowsShortcut: "Ctrl+Tab",
    macosShortcut: "Cmd+Option+Right",
    linuxShortcut: "Ctrl+Tab",
    popularity: 80,
    verified: true,
    aliases: ["next tab", "다음탭"],
    tags: ["tab", "navigation"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "이전 탭",
    description: "이전 탭으로 이동",
    windowsShortcut: "Ctrl+Shift+Tab",
    macosShortcut: "Cmd+Option+Left",
    linuxShortcut: "Ctrl+Shift+Tab",
    popularity: 75,
    verified: true,
    aliases: ["previous tab", "이전탭"],
    tags: ["tab", "navigation"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "확대",
    description: "페이지 확대",
    windowsShortcut: "Ctrl++",
    macosShortcut: "Cmd++",
    linuxShortcut: "Ctrl++",
    popularity: 70,
    verified: true,
    aliases: ["zoom in", "확대"],
    tags: ["zoom", "magnify"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "축소",
    description: "페이지 축소",
    windowsShortcut: "Ctrl+-",
    macosShortcut: "Cmd+-",
    linuxShortcut: "Ctrl+-",
    popularity: 65,
    verified: true,
    aliases: ["zoom out", "축소"],
    tags: ["zoom", "reduce"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "원래 크기",
    description: "100% 원래 크기로 복원",
    windowsShortcut: "Ctrl+0",
    macosShortcut: "Cmd+0",
    linuxShortcut: "Ctrl+0",
    popularity: 60,
    verified: true,
    aliases: ["reset zoom", "원래크기"],
    tags: ["zoom", "reset"]
  },
  {
    tool: "Google Chrome",
    category: "browser",
    title: "전체 화면",
    description: "전체 화면 모드 토글",
    windowsShortcut: "F11",
    macosShortcut: "Cmd+Ctrl+F",
    linuxShortcut: "F11",
    popularity: 65,
    verified: true,
    aliases: ["fullscreen", "전체화면"],
    tags: ["fullscreen", "mode"]
  },

  // Python IDE shortcuts
  {
    tool: "Python IDLE",
    category: "ide",
    title: "Python 실행",
    description: "Python 파일 실행",
    windowsShortcut: "F5",
    macosShortcut: "F5",
    linuxShortcut: "F5",
    popularity: 90,
    verified: true,
    aliases: ["run python", "파이썬실행"],
    tags: ["python", "run"]
  },
  {
    tool: "Python IDLE",
    category: "ide",
    title: "인터프리터 재시작",
    description: "Python 인터프리터 재시작",
    windowsShortcut: "Ctrl+F6",
    macosShortcut: "Cmd+F6",
    linuxShortcut: "Ctrl+F6",
    popularity: 75,
    verified: true,
    aliases: ["restart interpreter", "인터프리터재시작"],
    tags: ["python", "restart"]
  },
  {
    tool: "Python IDLE",
    category: "ide",
    title: "코드 완성",
    description: "자동 완성 제안",
    windowsShortcut: "Ctrl+Space",
    macosShortcut: "Cmd+Space",
    linuxShortcut: "Ctrl+Space",
    popularity: 85,
    verified: true,
    aliases: ["autocomplete", "자동완성"],
    tags: ["python", "autocomplete"]
  },
  {
    tool: "Python IDLE",
    category: "ide",
    title: "들여쓰기",
    description: "코드 들여쓰기",
    windowsShortcut: "Ctrl+]",
    macosShortcut: "Cmd+]",
    linuxShortcut: "Ctrl+]",
    popularity: 80,
    verified: true,
    aliases: ["indent", "들여쓰기"],
    tags: ["python", "indent"]
  },
  {
    tool: "Python IDLE",
    category: "ide",
    title: "내어쓰기",
    description: "코드 내어쓰기",
    windowsShortcut: "Ctrl+[",
    macosShortcut: "Cmd+[",
    linuxShortcut: "Ctrl+[",
    popularity: 75,
    verified: true,
    aliases: ["unindent", "내어쓰기"],
    tags: ["python", "unindent"]
  },

  // More communication tools
  {
    tool: "Microsoft Teams",
    category: "communication",
    title: "음소거 토글",
    description: "마이크 음소거 토글",
    windowsShortcut: "Ctrl+Shift+M",
    macosShortcut: "Cmd+Shift+M",
    linuxShortcut: "Ctrl+Shift+M",
    popularity: 90,
    verified: true,
    aliases: ["mute toggle", "음소거토글"],
    tags: ["audio", "mute"]
  },
  {
    tool: "Microsoft Teams",
    category: "communication",
    title: "비디오 토글",
    description: "비디오 켜기/끄기",
    windowsShortcut: "Ctrl+Shift+O",
    macosShortcut: "Cmd+Shift+O",
    linuxShortcut: "Ctrl+Shift+O",
    popularity: 85,
    verified: true,
    aliases: ["video toggle", "비디오토글"],
    tags: ["video", "toggle"]
  },
  {
    tool: "Microsoft Teams",
    category: "communication",
    title: "채팅 열기",
    description: "채팅 창 열기",
    windowsShortcut: "Ctrl+Shift+Space",
    macosShortcut: "Cmd+Shift+Space",
    linuxShortcut: "Ctrl+Shift+Space",
    popularity: 80,
    verified: true,
    aliases: ["open chat", "채팅열기"],
    tags: ["chat", "open"]
  },
  {
    tool: "Microsoft Teams",
    category: "communication",
    title: "통화 수락",
    description: "수신 통화 수락",
    windowsShortcut: "Ctrl+Shift+S",
    macosShortcut: "Cmd+Shift+S",
    linuxShortcut: "Ctrl+Shift+S",
    popularity: 75,
    verified: true,
    aliases: ["accept call", "통화수락"],
    tags: ["call", "accept"]
  },
  {
    tool: "Microsoft Teams",
    category: "communication",
    title: "통화 거부",
    description: "수신 통화 거부",
    windowsShortcut: "Ctrl+Shift+D",
    macosShortcut: "Cmd+Shift+D",
    linuxShortcut: "Ctrl+Shift+D",
    popularity: 70,
    verified: true,
    aliases: ["decline call", "통화거부"],
    tags: ["call", "decline"]
  },

  // More productivity tools
  {
    tool: "Obsidian",
    category: "productivity",
    title: "새 노트",
    description: "새 노트 생성",
    windowsShortcut: "Ctrl+N",
    macosShortcut: "Cmd+N",
    linuxShortcut: "Ctrl+N",
    popularity: 85,
    verified: true,
    aliases: ["new note", "새노트"],
    tags: ["note", "new"]
  },
  {
    tool: "Obsidian",
    category: "productivity",
    title: "빠른 스위처",
    description: "파일 빠른 검색",
    windowsShortcut: "Ctrl+O",
    macosShortcut: "Cmd+O",
    linuxShortcut: "Ctrl+O",
    popularity: 90,
    verified: true,
    aliases: ["quick switcher", "빠른스위처"],
    tags: ["search", "quick"]
  },
  {
    tool: "Obsidian",
    category: "productivity",
    title: "그래프 보기",
    description: "그래프 보기 열기",
    windowsShortcut: "Ctrl+G",
    macosShortcut: "Cmd+G",
    linuxShortcut: "Ctrl+G",
    popularity: 75,
    verified: true,
    aliases: ["graph view", "그래프보기"],
    tags: ["graph", "view"]
  },
  {
    tool: "Obsidian",
    category: "productivity",
    title: "링크 삽입",
    description: "내부 링크 삽입",
    windowsShortcut: "Ctrl+K",
    macosShortcut: "Cmd+K",
    linuxShortcut: "Ctrl+K",
    popularity: 80,
    verified: true,
    aliases: ["insert link", "링크삽입"],
    tags: ["link", "insert"]
  },
  {
    tool: "Obsidian",
    category: "productivity",
    title: "미리보기 모드",
    description: "편집/미리보기 모드 전환",
    windowsShortcut: "Ctrl+E",
    macosShortcut: "Cmd+E",
    linuxShortcut: "Ctrl+E",
    popularity: 70,
    verified: true,
    aliases: ["preview mode", "미리보기모드"],
    tags: ["preview", "mode"]
  },

  // More media tools
  {
    tool: "VLC Media Player",
    category: "media",
    title: "재생/일시정지",
    description: "미디어 재생 또는 일시정지",
    windowsShortcut: "Space",
    macosShortcut: "Space",
    linuxShortcut: "Space",
    popularity: 95,
    verified: true,
    aliases: ["play pause", "재생일시정지"],
    tags: ["media", "play"]
  },
  {
    tool: "VLC Media Player",
    category: "media",
    title: "전체 화면",
    description: "전체 화면 토글",
    windowsShortcut: "F",
    macosShortcut: "F",
    linuxShortcut: "F",
    popularity: 85,
    verified: true,
    aliases: ["fullscreen", "전체화면"],
    tags: ["media", "fullscreen"]
  },
  {
    tool: "VLC Media Player",
    category: "media",
    title: "볼륨 증가",
    description: "볼륨 증가",
    windowsShortcut: "Ctrl+Up",
    macosShortcut: "Cmd+Up",
    linuxShortcut: "Ctrl+Up",
    popularity: 80,
    verified: true,
    aliases: ["volume up", "볼륨증가"],
    tags: ["media", "volume"]
  },
  {
    tool: "VLC Media Player",
    category: "media",
    title: "볼륨 감소",
    description: "볼륨 감소",
    windowsShortcut: "Ctrl+Down",
    macosShortcut: "Cmd+Down",
    linuxShortcut: "Ctrl+Down",
    popularity: 75,
    verified: true,
    aliases: ["volume down", "볼륨감소"],
    tags: ["media", "volume"]
  },
  {
    tool: "VLC Media Player",
    category: "media",
    title: "빨리 감기",
    description: "10초 빨리 감기",
    windowsShortcut: "Right",
    macosShortcut: "Right",
    linuxShortcut: "Right",
    popularity: 85,
    verified: true,
    aliases: ["fast forward", "빨리감기"],
    tags: ["media", "seek"]
  },
  {
    tool: "VLC Media Player",
    category: "media",
    title: "되감기",
    description: "10초 되감기",
    windowsShortcut: "Left",
    macosShortcut: "Left",
    linuxShortcut: "Left",
    popularity: 80,
    verified: true,
    aliases: ["rewind", "되감기"],
    tags: ["media", "seek"]
  },

  // More office tools
  {
    tool: "Microsoft Word",
    category: "office",
    title: "굵게",
    description: "선택한 텍스트 굵게",
    windowsShortcut: "Ctrl+B",
    macosShortcut: "Cmd+B",
    linuxShortcut: "Ctrl+B",
    popularity: 90,
    verified: true,
    aliases: ["bold", "굵게"],
    tags: ["format", "bold"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "기울임꼴",
    description: "선택한 텍스트 기울임꼴",
    windowsShortcut: "Ctrl+I",
    macosShortcut: "Cmd+I",
    linuxShortcut: "Ctrl+I",
    popularity: 85,
    verified: true,
    aliases: ["italic", "기울임꼴"],
    tags: ["format", "italic"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "밑줄",
    description: "선택한 텍스트 밑줄",
    windowsShortcut: "Ctrl+U",
    macosShortcut: "Cmd+U",
    linuxShortcut: "Ctrl+U",
    popularity: 80,
    verified: true,
    aliases: ["underline", "밑줄"],
    tags: ["format", "underline"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "가운데 정렬",
    description: "텍스트 가운데 정렬",
    windowsShortcut: "Ctrl+E",
    macosShortcut: "Cmd+E",
    linuxShortcut: "Ctrl+E",
    popularity: 75,
    verified: true,
    aliases: ["center align", "가운데정렬"],
    tags: ["format", "align"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "왼쪽 정렬",
    description: "텍스트 왼쪽 정렬",
    windowsShortcut: "Ctrl+L",
    macosShortcut: "Cmd+L",
    linuxShortcut: "Ctrl+L",
    popularity: 70,
    verified: true,
    aliases: ["left align", "왼쪽정렬"],
    tags: ["format", "align"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "오른쪽 정렬",
    description: "텍스트 오른쪽 정렬",
    windowsShortcut: "Ctrl+R",
    macosShortcut: "Cmd+R",
    linuxShortcut: "Ctrl+R",
    popularity: 65,
    verified: true,
    aliases: ["right align", "오른쪽정렬"],
    tags: ["format", "align"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "글꼴 크기 증가",
    description: "글꼴 크기 증가",
    windowsShortcut: "Ctrl+Shift+>",
    macosShortcut: "Cmd+Shift+>",
    linuxShortcut: "Ctrl+Shift+>",
    popularity: 70,
    verified: true,
    aliases: ["increase font size", "글꼴크기증가"],
    tags: ["format", "font"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "글꼴 크기 감소",
    description: "글꼴 크기 감소",
    windowsShortcut: "Ctrl+Shift+<",
    macosShortcut: "Cmd+Shift+<",
    linuxShortcut: "Ctrl+Shift+<",
    popularity: 65,
    verified: true,
    aliases: ["decrease font size", "글꼴크기감소"],
    tags: ["format", "font"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "페이지 나누기",
    description: "페이지 나누기 삽입",
    windowsShortcut: "Ctrl+Enter",
    macosShortcut: "Cmd+Enter",
    linuxShortcut: "Ctrl+Enter",
    popularity: 75,
    verified: true,
    aliases: ["page break", "페이지나누기"],
    tags: ["page", "break"]
  },
  {
    tool: "Microsoft Word",
    category: "office",
    title: "단락 나누기",
    description: "단락 나누기 삽입",
    windowsShortcut: "Shift+Enter",
    macosShortcut: "Shift+Enter",
    linuxShortcut: "Shift+Enter",
    popularity: 70,
    verified: true,
    aliases: ["line break", "단락나누기"],
    tags: ["line", "break"]
  },

  // Additional shortcuts (이 부분에 나머지 300+ 단축키들이 계속 포함됩니다)
  // 공간상 일부만 표시하고 나머지는 이어집니다...
];

// 각 단축키에 ID 추가하는 헬퍼 함수
export const getShortcutsWithIds = () => {
  return shortcutsData.map((shortcut, index) => ({
    id: index + 1,
    ...shortcut
  }));
};
